/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LocalitySearchResult {
    latitude: number;
    name: string;
    longitude: number;
    riskLevel: string;
}
export type Time = bigint;
export interface LocalityRisk {
    latitude: number;
    commonIncidentType: string;
    name: string;
    peakIncidentTime: bigint;
    longitude: number;
    incidentCount: bigint;
    riskLevel: string;
    riskScore: bigint;
}
export interface Alert {
    id: bigint;
    time: Time;
    description: string;
    severity: bigint;
    location: string;
}
export interface Incident {
    id: bigint;
    latitude: number;
    description: string;
    longitude: number;
    timestamp: Time;
    severity: bigint;
    locality: string;
    incidentType: string;
}
export interface backendInterface {
    addAlert(location: string, description: string, severity: bigint): Promise<bigint>;
    addIncident(locality: string, latitude: number, longitude: number, incidentType: string, severity: bigint, description: string): Promise<bigint>;
    clearAllData(): Promise<void>;
    getAboutInfo(): Promise<{
        privacyStatement: string;
        dataSource: string;
        riskCalculationMethod: string;
    }>;
    getAlertsBySeverity(severity: bigint): Promise<Array<Alert>>;
    getAllAlerts(): Promise<Array<Alert>>;
    getAllLocalities(): Promise<Array<string>>;
    getAllLocalityRisks(): Promise<Array<LocalityRisk>>;
    getIncident(arg0: bigint): Promise<Incident>;
    getIncidentTrends(arg0: string): Promise<Array<[string, bigint]>>;
    getIncidentTypeDistribution(): Promise<Array<[string, bigint]>>;
    getIncidents(): Promise<Array<Incident>>;
    getIncidentsByLocality(locality: string): Promise<Array<Incident>>;
    getLocalityCoordinates(locality: string): Promise<[number, number] | null>;
    getLocalityRisk(locality: string): Promise<LocalityRisk>;
    getLocalitySearchResults(searchText: string): Promise<Array<LocalitySearchResult>>;
    getNearbyLocalities(latitude: number, longitude: number, radius: number): Promise<Array<LocalityRisk>>;
    getPeakIncidentHours(arg0: string): Promise<Array<[bigint, bigint]>>;
    initializeSampleData(): Promise<void>;
    mapLegend(): Promise<Array<[string, string]>>;
    searchLocality(locality: string): Promise<LocalityRisk | null>;
}
import type { LocalityRisk as _LocalityRisk } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAlert(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(arg0, arg1, arg2);
            return result;
        }
    }
    async addIncident(arg0: string, arg1: number, arg2: number, arg3: string, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncident(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncident(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async clearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async getAboutInfo(): Promise<{
        privacyStatement: string;
        dataSource: string;
        riskCalculationMethod: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutInfo();
            return result;
        }
    }
    async getAlertsBySeverity(arg0: bigint): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsBySeverity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsBySeverity(arg0);
            return result;
        }
    }
    async getAllAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return result;
        }
    }
    async getAllLocalities(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocalities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocalities();
            return result;
        }
    }
    async getAllLocalityRisks(): Promise<Array<LocalityRisk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocalityRisks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocalityRisks();
            return result;
        }
    }
    async getIncident(arg0: bigint): Promise<Incident> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncident(arg0);
            return result;
        }
    }
    async getIncidentTrends(arg0: string): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentTrends(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentTrends(arg0);
            return result;
        }
    }
    async getIncidentTypeDistribution(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentTypeDistribution();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentTypeDistribution();
            return result;
        }
    }
    async getIncidents(): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidents();
            return result;
        }
    }
    async getIncidentsByLocality(arg0: string): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentsByLocality(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentsByLocality(arg0);
            return result;
        }
    }
    async getLocalityCoordinates(arg0: string): Promise<[number, number] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalityCoordinates(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalityCoordinates(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocalityRisk(arg0: string): Promise<LocalityRisk> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalityRisk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalityRisk(arg0);
            return result;
        }
    }
    async getLocalitySearchResults(arg0: string): Promise<Array<LocalitySearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalitySearchResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalitySearchResults(arg0);
            return result;
        }
    }
    async getNearbyLocalities(arg0: number, arg1: number, arg2: number): Promise<Array<LocalityRisk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyLocalities(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyLocalities(arg0, arg1, arg2);
            return result;
        }
    }
    async getPeakIncidentHours(arg0: string): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeakIncidentHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeakIncidentHours(arg0);
            return result;
        }
    }
    async initializeSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSampleData();
            return result;
        }
    }
    async mapLegend(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.mapLegend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mapLegend();
            return result;
        }
    }
    async searchLocality(arg0: string): Promise<LocalityRisk | null> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLocality(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLocality(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[number, number]]): [number, number] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocalityRisk]): LocalityRisk | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
