/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'time' : Time,
  'description' : string,
  'severity' : bigint,
  'location' : string,
}
export interface Incident {
  'id' : bigint,
  'latitude' : number,
  'description' : string,
  'longitude' : number,
  'timestamp' : Time,
  'severity' : bigint,
  'locality' : string,
  'incidentType' : string,
}
export interface LocalityRisk {
  'latitude' : number,
  'commonIncidentType' : string,
  'name' : string,
  'peakIncidentTime' : bigint,
  'longitude' : number,
  'incidentCount' : bigint,
  'riskLevel' : string,
  'riskScore' : bigint,
}
export interface LocalitySearchResult {
  'latitude' : number,
  'name' : string,
  'longitude' : number,
  'riskLevel' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAlert' : ActorMethod<[string, string, bigint], bigint>,
  'addIncident' : ActorMethod<
    [string, number, number, string, bigint, string],
    bigint
  >,
  'clearAllData' : ActorMethod<[], undefined>,
  'getAboutInfo' : ActorMethod<
    [],
    {
      'privacyStatement' : string,
      'dataSource' : string,
      'riskCalculationMethod' : string,
    }
  >,
  'getAlertsBySeverity' : ActorMethod<[bigint], Array<Alert>>,
  'getAllAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllLocalities' : ActorMethod<[], Array<string>>,
  'getAllLocalityRisks' : ActorMethod<[], Array<LocalityRisk>>,
  'getIncident' : ActorMethod<[bigint], Incident>,
  'getIncidentTrends' : ActorMethod<[string], Array<[string, bigint]>>,
  'getIncidentTypeDistribution' : ActorMethod<[], Array<[string, bigint]>>,
  'getIncidents' : ActorMethod<[], Array<Incident>>,
  'getIncidentsByLocality' : ActorMethod<[string], Array<Incident>>,
  'getLocalityCoordinates' : ActorMethod<[string], [] | [[number, number]]>,
  'getLocalityRisk' : ActorMethod<[string], LocalityRisk>,
  'getLocalitySearchResults' : ActorMethod<
    [string],
    Array<LocalitySearchResult>
  >,
  'getNearbyLocalities' : ActorMethod<
    [number, number, number],
    Array<LocalityRisk>
  >,
  'getPeakIncidentHours' : ActorMethod<[string], Array<[bigint, bigint]>>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'mapLegend' : ActorMethod<[], Array<[string, string]>>,
  'searchLocality' : ActorMethod<[string], [] | [LocalityRisk]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];