/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'time' : Time,
  'description' : IDL.Text,
  'severity' : IDL.Nat,
  'location' : IDL.Text,
});
export const LocalityRisk = IDL.Record({
  'latitude' : IDL.Float64,
  'commonIncidentType' : IDL.Text,
  'name' : IDL.Text,
  'peakIncidentTime' : IDL.Nat,
  'longitude' : IDL.Float64,
  'incidentCount' : IDL.Nat,
  'riskLevel' : IDL.Text,
  'riskScore' : IDL.Nat,
});
export const Incident = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
  'severity' : IDL.Nat,
  'locality' : IDL.Text,
  'incidentType' : IDL.Text,
});
export const LocalitySearchResult = IDL.Record({
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'riskLevel' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addIncident' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'clearAllData' : IDL.Func([], [], []),
  'getAboutInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'privacyStatement' : IDL.Text,
          'dataSource' : IDL.Text,
          'riskCalculationMethod' : IDL.Text,
        }),
      ],
      [],
    ),
  'getAlertsBySeverity' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllLocalities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllLocalityRisks' : IDL.Func([], [IDL.Vec(LocalityRisk)], ['query']),
  'getIncident' : IDL.Func([IDL.Nat], [Incident], ['query']),
  'getIncidentTrends' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getIncidentTypeDistribution' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'getIncidentsByLocality' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Incident)],
      ['query'],
    ),
  'getLocalityCoordinates' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64))],
      ['query'],
    ),
  'getLocalityRisk' : IDL.Func([IDL.Text], [LocalityRisk], ['query']),
  'getLocalitySearchResults' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LocalitySearchResult)],
      ['query'],
    ),
  'getNearbyLocalities' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(LocalityRisk)],
      ['query'],
    ),
  'getPeakIncidentHours' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [],
    ),
  'initializeSampleData' : IDL.Func([], [], []),
  'mapLegend' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'searchLocality' : IDL.Func([IDL.Text], [IDL.Opt(LocalityRisk)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'time' : Time,
    'description' : IDL.Text,
    'severity' : IDL.Nat,
    'location' : IDL.Text,
  });
  const LocalityRisk = IDL.Record({
    'latitude' : IDL.Float64,
    'commonIncidentType' : IDL.Text,
    'name' : IDL.Text,
    'peakIncidentTime' : IDL.Nat,
    'longitude' : IDL.Float64,
    'incidentCount' : IDL.Nat,
    'riskLevel' : IDL.Text,
    'riskScore' : IDL.Nat,
  });
  const Incident = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
    'severity' : IDL.Nat,
    'locality' : IDL.Text,
    'incidentType' : IDL.Text,
  });
  const LocalitySearchResult = IDL.Record({
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'riskLevel' : IDL.Text,
  });
  
  return IDL.Service({
    'addAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addIncident' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'clearAllData' : IDL.Func([], [], []),
    'getAboutInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'privacyStatement' : IDL.Text,
            'dataSource' : IDL.Text,
            'riskCalculationMethod' : IDL.Text,
          }),
        ],
        [],
      ),
    'getAlertsBySeverity' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllLocalities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllLocalityRisks' : IDL.Func([], [IDL.Vec(LocalityRisk)], ['query']),
    'getIncident' : IDL.Func([IDL.Nat], [Incident], ['query']),
    'getIncidentTrends' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getIncidentTypeDistribution' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'getIncidentsByLocality' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Incident)],
        ['query'],
      ),
    'getLocalityCoordinates' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64))],
        ['query'],
      ),
    'getLocalityRisk' : IDL.Func([IDL.Text], [LocalityRisk], ['query']),
    'getLocalitySearchResults' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LocalitySearchResult)],
        ['query'],
      ),
    'getNearbyLocalities' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(LocalityRisk)],
        ['query'],
      ),
    'getPeakIncidentHours' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [],
      ),
    'initializeSampleData' : IDL.Func([], [], []),
    'mapLegend' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'searchLocality' : IDL.Func([IDL.Text], [IDL.Opt(LocalityRisk)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };